// A deliberately tiny JSON Schema subset — enough to describe a tool's input to
// Bedrock and to VALIDATE what comes back, with no dependency.
//
// Validation is not ceremony here. Tool input is generated by a language model,
// so `{"hours": "about six"}` and `{"instanceTye": "p5.48xlarge"}` are things
// that actually happen. Without a check, a string lands in an arithmetic
// expression and the user is shown `$NaN/hr`, or a typo'd key silently becomes a
// default. Both present as answers. So input is validated before a handler runs,
// and a failure is recorded as a failure.

/** The JSON Schema subset advisor-ts uses for tool inputs. */
export interface JsonSchema {
  type: "object" | "string" | "number" | "integer" | "boolean" | "array";
  description?: string;
  /** For `object`. */
  properties?: Record<string, JsonSchema>;
  /** For `object` — property names that must be present and non-null. */
  required?: string[];
  /** For `array`. */
  items?: JsonSchema;
  /** For `string` — the permitted values. */
  enum?: string[];
  /** For `number`/`integer`. */
  minimum?: number;
  maximum?: number;
}

/**
 * Validate `value` against `schema`, returning a list of human-readable problems
 * — empty means valid. Returns ALL problems rather than the first, because the
 * list goes back to the model as a tool error and one round-trip per typo is
 * both slow and billable.
 *
 * Unknown properties are reported. A model that invents a key has usually
 * misunderstood the tool, and silently dropping the key would leave the caller
 * with a plausible-looking result computed from defaults.
 */
export function validate(value: unknown, schema: JsonSchema, path = ""): string[] {
  const at = path || "input";
  const errs: string[] = [];

  switch (schema.type) {
    case "object": {
      if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return [`${at}: expected an object, got ${describe(value)}`];
      }
      const obj = value as Record<string, unknown>;
      const props = schema.properties ?? {};
      for (const key of schema.required ?? []) {
        if (obj[key] === undefined || obj[key] === null) {
          errs.push(`${at}.${key}: required`);
        }
      }
      for (const [key, val] of Object.entries(obj)) {
        const sub = props[key];
        if (!sub) {
          errs.push(`${at}.${key}: unknown property (expected one of: ${Object.keys(props).join(", ")})`);
          continue;
        }
        // An omitted optional is fine; an explicit null is not, since it would
        // reach the handler as a value.
        if (val === undefined) continue;
        errs.push(...validate(val, sub, `${at}.${key}`));
      }
      return errs;
    }
    case "array": {
      if (!Array.isArray(value)) return [`${at}: expected an array, got ${describe(value)}`];
      if (schema.items) {
        value.forEach((v, i) => errs.push(...validate(v, schema.items!, `${at}[${i}]`)));
      }
      return errs;
    }
    case "string": {
      if (typeof value !== "string") return [`${at}: expected a string, got ${describe(value)}`];
      if (schema.enum && !schema.enum.includes(value)) {
        return [`${at}: "${value}" is not one of: ${schema.enum.join(", ")}`];
      }
      return errs;
    }
    case "integer":
    case "number": {
      // Explicitly NOT coercing "8" → 8. A tool that accepts a stringified number
      // teaches the model that loose types work, and the one place it matters —
      // a price or an hour count — is the place a silent coercion does damage.
      if (typeof value !== "number" || Number.isNaN(value)) {
        return [`${at}: expected a number, got ${describe(value)}`];
      }
      if (schema.type === "integer" && !Number.isInteger(value)) {
        errs.push(`${at}: expected a whole number, got ${value}`);
      }
      if (schema.minimum !== undefined && value < schema.minimum) {
        errs.push(`${at}: ${value} is below the minimum ${schema.minimum}`);
      }
      if (schema.maximum !== undefined && value > schema.maximum) {
        errs.push(`${at}: ${value} is above the maximum ${schema.maximum}`);
      }
      return errs;
    }
    case "boolean": {
      if (typeof value !== "boolean") return [`${at}: expected true or false, got ${describe(value)}`];
      return errs;
    }
    default:
      return [`${at}: unsupported schema type`];
  }
}

function describe(value: unknown): string {
  if (value === null) return "null";
  if (Array.isArray(value)) return "an array";
  if (typeof value === "string") return `a string ("${value}")`;
  return `a ${typeof value}`;
}
